### ISSUE TITLE
Iframe size only updates on window resize, not on child size change

### ISSUE THREAD

**Issue by anderser** [npr/responsiveiframe#10]
I have a child page in which the user interacts and elements are shown/hidden and the size of the content changes. But in the parent page the iframe's size is not updated until I manually resize the browser. Isn't that supposed to happen when content in child changes size? Using Chrome. Child and parent are on different domains.

child code:

``` javascript
<script>
          var ri = responsiveIframe();
          ri.allowResponsiveEmbedding();
</script>
```

in parent (with jquery 2.0.0):

``` javascript
<script>
        ;(function($){
            $(function(){
                $('#theiframe').responsiveIframe({ xdomain: '*'});
            });
        })(jQuery);
    </script>

    <div id="iframecontainer" style="width: 100%;">
        <iframe id="theiframe" src="http://urlofchildpage" style="width: 100%; padding: 0px;margin: 0; border: none; display: block;height:0px; overflow: hidden;" ></iframe>
    </div>
```

**Comment by thecodemill** [comment]
Hi @anderser, did you manage to find a solution to this in the end? I'm having the same problem and wondered why you closed the issue?
