### ISSUE TITLE
`orgin` should be `origin`

### ISSUE THREAD

**Issue by elijahr** [npr/responsiveiframe#16]
I believe the check to see if the iframe embeds a `file:///` url will always be false because of a typo on [line 49](https://github.com/npr/responsiveiframe/blob/49e520f7439b4903ef3634aa8e5ee8cf05aaf83d/src/jquery.responsiveiframe.js#L49) of jquery.responsiveiframe.js on HEAD.

**Comment by mbseid** [comment]
Thanks for reporting this. I am going to take a look and give a quick fix.

**Comment by elijahr** [comment]
:+1: Thank you for your quick turnaround.
