### ISSUE TITLE
Doesn’t work with nested iframes

### ISSUE THREAD

**Issue by supermueller** [npr/responsiveiframe#25]
If you have an iframe in an document wicht itself is embedded in an iframe the script fails. The solution is to post the message to the parent window (and not to the top window):

```
  ResponsiveIframe.prototype.messageParent = function(scrollTop) {
    var h = document.body.offsetHeight;
    h = (scrollTop)? h+'s':h;
    if(parent.postMessage){
      parent.postMessage( h , '*');
    } else {
      window.location.hash = 'h'+h;
    }
  };
```

**Comment by inadarei** [comment]
Please post a pull request with the solution. 

Thanks

**Comment by supermueller** [comment]
I have post a pull request for the first time so I hope I have done it all right.

**Comment by inadarei** [comment]
Done. Thanks!

**Comment by supermueller** [comment]
It's been a pleasure.
